import React from 'react';
import Card from '../components/ui/Card';

const FAQ = () => {
  const faqs = [
    {
      question: "What is AI-generated video content?",
      answer: "AI-generated video content refers to videos created using artificial intelligence algorithms. These videos can be customized and produced quickly without the need for traditional video production methods."
    },
    {
      question: "How can I use the videos from iVisionary?",
      answer: "You can use our videos for various purposes, including marketing campaigns, social media content, website backgrounds, and more. The specific usage rights depend on the license you purchase with each video."
    },
    {
      question: "Are the AI-generated videos unique?",
      answer: "Yes, each video generated by our AI is unique. However, as with any AI-generated content, there may be similarities in style or elements across different videos."
    },
    {
      question: "Can I request custom AI-generated videos?",
      answer: "Yes, we offer custom video generation services for our premium subscribers. You can provide specific requirements, and our AI will create videos tailored to your needs."
    },
    {
      question: "What file formats are available for download?",
      answer: "We offer downloads in popular video formats including MP4, MOV, and AVI. The specific formats available may vary depending on your subscription level."
    }
  ];

  return (
    <div className="container mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold mb-6 text-white">Frequently Asked Questions</h1>
      <div className="space-y-4">
        {faqs.map((faq, index) => (
          <Card key={index}>
            <h2 className="text-xl font-semibold mb-2 text-white">{faq.question}</h2>
            <p className="text-gray-300">{faq.answer}</p>
          </Card>
        ))}
      </div>
    </div>
  );
};

export default FAQ;